/**
 * This module was automatically generated by `ts-interface-builder`
 */
import * as t from "ts-interface-checker";
// tslint:disable:object-literal-key-quotes

export const CommentSetting = t.union(t.lit('all'), t.lit('relevant'), t.lit('none'));

export const NotificationPrefs = t.iface([], {
  "docChanges": t.opt("boolean"),
  "comments": t.opt("CommentSetting"),
});

export const NotificationPrefsBundle = t.iface([], {
  "docDefaults": t.opt("NotificationPrefs"),
  "currentUser": t.opt("NotificationPrefs"),
});

const exportedTypeSuite: t.ITypeSuite = {
  CommentSetting,
  NotificationPrefs,
  NotificationPrefsBundle,
};
export default exportedTypeSuite;
