/**
 * This module was automatically generated by `ts-interface-builder`
 */
import * as t from "ts-interface-checker";
// tslint:disable:object-literal-key-quotes

export const Address = t.iface([], {
  "email": "string",
  "name": "string",
});

export const NodemailerSender = t.iface(["Address"], {
  "docNotificationsFrom": t.opt("string"),
  "docNotificationsReplyTo": t.opt("string"),
});

const exportedTypeSuite: t.ITypeSuite = {
  Address,
  NodemailerSender,
};
export default exportedTypeSuite;
